import type { SportId } from '@/app/lib/sports';

export const STATUS_OPTS: Record<SportId, string[]> = {
  cricket: [],
  basketball: [
    'Quarter I',
    'Quarter II',
    'Half Time',
    'Quarter III',
    'Quarter IV',
    'Full time',
    'OT',
  ],
  football: [
    'Kick-off',
    '1st half',
    'Half time',
    '2nd half',
    'Full time',
    'Extra time AET',
  ],
  tennis: [
    'Match started',
    'Set 1',
    'Set 2',
    'Set 3',
    'Set 4',
    'Set 5',
    'Match complete',
  ],
  badminton: ['Game 1', 'Game 2', 'Game 3', 'Match complete'],
  volleyball: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5', 'Match complete'],
  kabaddi: ['1st half', 'Half time', '2nd half', 'Match complete'],
  frisbee: ['1st half', 'Half time', '2nd half', 'Game complete'],
  carrom: ['Board 1', 'Board 2', 'Board 3', 'Match complete'],
  chess: ['Game started', 'Mid-game', 'Endgame', 'Game complete'],
  hockey: ['Period 1', 'Period 2', 'Period 3', 'Overtime', 'Match complete'],
  khokho: ['Inning 1', 'Inning 2', 'Inning 3', 'Inning 4', 'Match complete'],
  powerlifting: ['Squat', 'Bench Press', 'Deadlift', 'Competition complete'],
  skating: ['Race started', 'In progress', 'Race complete'],
  '8ball': [
    'Frame 1',
    'Frame 2',
    'Frame 3',
    'Frame 4',
    'Frame 5',
    'Match complete',
  ],
  snooker: [
    'Frame 1',
    'Frame 2',
    'Frame 3',
    'Frame 4',
    'Frame 5',
    'Match complete',
  ],
  squash: ['Game 1', 'Game 2', 'Game 3', 'Game 4', 'Game 5', 'Match complete'],
  swimming: ['In progress', 'Completed'],
  tabletennis: [
    'Game 1',
    'Game 2',
    'Game 3',
    'Game 4',
    'Game 5',
    'Match complete',
  ],
  throwball: ['Set 1', 'Set 2', 'Set 3', 'Match complete'],
};

export const DEFAULTS: Record<SportId, any> = {
  cricket: {},
  basketball: {
    teamA: '',
    teamB: '',
    scoreA: 0,
    scoreB: 0,
    currentQuarter: 1,
    gameClock: '12:00',
    shotClock: 24,
    quarterScoresA: [0, 0, 0, 0],
    quarterScoresB: [0, 0, 0, 0],
    foulsA: 0,
    foulsB: 0,
    status: 'Quarter I',
  },
  football: {
    teamA: '',
    teamB: '',
    scoreA: 0,
    scoreB: 0,
    matchTime: 0,
    half: 1,
    clockRunning: false,
    events: [],
    status: 'Kick-off',
  },
  tennis: {
    player1: '',
    player2: '',
    setsPlayer1: [],
    setsPlayer2: [],
    currentSet: 1,
    currentGameScorePlayer1: '0',
    currentGameScorePlayer2: '0',
    server: 1,
    surface: '',
    status: 'Match started',
  },
  badminton: {
    player1: '',
    player2: '',
    gamesPlayer1: [],
    gamesPlayer2: [],
    currentGame: 1,
    currentPointsPlayer1: 0,
    currentPointsPlayer2: 0,
    server: 1,
    bestOf: 3,
    status: 'Game 1',
  },
  volleyball: {
    teamA: '',
    teamB: '',
    setsTeamA: [],
    setsTeamB: [],
    currentSet: 1,
    currentPointsTeamA: 0,
    currentPointsTeamB: 0,
    setWinsA: 0,
    setWinsB: 0,
    bestOf: 5,
    status: 'Set 1',
  },
  kabaddi: {
    teamA: '',
    teamB: '',
    scoreA: 0,
    scoreB: 0,
    playersOnMatA: 7,
    playersOnMatB: 7,
    raidTimer: 30,
    raidingTeam: '',
    bonusActive: false,
    superRaidActive: false,
    half: 1,
    timeRemaining: '20:00',
    clockRunning: false,
    status: '1st half',
  },
  frisbee: {
    teamA: '',
    teamB: '',
    scoreA: 0,
    scoreB: 0,
    timeRemaining: '48:00',
    pointCap: 21,
    possession: '',
    status: '1st half',
  },
  carrom: {
    player1: '',
    player2: '',
    scorePlayer1: 0,
    scorePlayer2: 0,
    currentBoard: 1,
    bestOf: 3,
    board1Player1: 0,
    board2Player1: 0,
    board3Player1: 0,
    board1Player2: 0,
    board2Player2: 0,
    board3Player2: 0,
    striker: 1,
    status: 'Board 1',
  },
  chess: {
    player1: '',
    player2: '',
    timePlayer1: '10:00',
    timePlayer2: '10:00',
    moveCount: 0,
    currentTurn: 1,
    timeControl: '10+0',
    result: '',
    status: 'Game started',
  },
  hockey: {
    teamA: '',
    teamB: '',
    scoreA: 0,
    scoreB: 0,
    currentPeriod: 1,
    matchTime: '0:00',
    clockRunning: false,
    periodScoresA: [0, 0, 0],
    periodScoresB: [0, 0, 0],
    penaltiesA: 0,
    penaltiesB: 0,
    status: 'Period 1',
  },
  khokho: {
    teamA: '',
    teamB: '',
    scoreA: 0,
    scoreB: 0,
    currentInning: 1,
    chasingTeam: 'A',
    defendersRemaining: 7,
    timeRemaining: '7:00',
    inning1ScoreA: 0,
    inning2ScoreA: 0,
    inning1ScoreB: 0,
    inning2ScoreB: 0,
    status: 'Inning 1',
  },
  powerlifting: {
    athlete1: '',
    athlete2: '',
    squatAthlete1: 0,
    benchAthlete1: 0,
    deadliftAthlete1: 0,
    squatAthlete2: 0,
    benchAthlete2: 0,
    deadliftAthlete2: 0,
    totalAthlete1: 0,
    totalAthlete2: 0,
    currentLift: 'squat',
    weightClass: '',
    status: 'Squat',
  },
  skating: {
    athlete1: '',
    athlete2: '',
    time1: '',
    time2: '',
    distance: '',
    eventType: 'speed',
    scoreAthlete1: 0,
    scoreAthlete2: 0,
    status: 'Race started',
  },
  '8ball': {
    player1: '',
    player2: '',
    framesPlayer1: 0,
    framesPlayer2: 0,
    currentFrame: 1,
    bestOf: 5,
    ballsRemainingPlayer1: 7,
    ballsRemainingPlayer2: 7,
    onBreak: 1,
    status: 'Frame 1',
  },
  snooker: {
    player1: '',
    player2: '',
    framesPlayer1: 0,
    framesPlayer2: 0,
    currentFrame: 1,
    currentScorePlayer1: 0,
    currentScorePlayer2: 0,
    bestOf: 7,
    onTable: 1,
    remainingPoints: 147,
    status: 'Frame 1',
  },
  squash: {
    player1: '',
    player2: '',
    gamesPlayer1: [],
    gamesPlayer2: [],
    currentGame: 1,
    currentPointsPlayer1: 0,
    currentPointsPlayer2: 0,
    server: 1,
    bestOf: 5,
    status: 'Game 1',
  },
  swimming: {
    swimmer1: '',
    swimmer2: '',
    time1: '',
    time2: '',
    distance: '',
    stroke: '',
    lane1: 0,
    lane2: 0,
    status: 'Heat started',
  },
  tabletennis: {
    player1: '',
    player2: '',
    gamesPlayer1: [],
    gamesPlayer2: [],
    currentGame: 1,
    currentPointsPlayer1: 0,
    currentPointsPlayer2: 0,
    server: 1,
    bestOf: 5,
    status: 'Game 1',
  },
  throwball: {
    teamA: '',
    teamB: '',
    setsTeamA: [],
    setsTeamB: [],
    currentSet: 1,
    currentPointsTeamA: 0,
    currentPointsTeamB: 0,
    setWinsA: 0,
    setWinsB: 0,
    bestOf: 3,
    servingTeam: 'A',
    status: 'Set 1',
  },
};
