const initialMatchesBySport = {
  cricket: [
    {
      id: 1,
      teamA: "Mumbai Indians",
      teamB: "Chennai Super Kings",
      scoreA: { runs: 184, wickets: 6, overs: "20.0" },
      scoreB: { runs: 142, wickets: 8, overs: "18.4" },
      status: "Mumbai Indians won by 42 runs",
      details: {
        summary: "MOTM: Rohit Sharma - 68(42)",
      },
    },
    {
      id: 2,
      teamA: "Royal Challengers",
      teamB: "Delhi Capitals",
      scoreA: { runs: 156, wickets: 4, overs: "16.2" },
      scoreB: { runs: 125, wickets: 9, overs: "20.0" },
      status: "Match in progress",
      details: {
        striker: { name: "V. Kohli", runs: 72, balls: 45 },
        nonStriker: { name: "G. Maxwell", runs: 14, balls: 8 },
        bowler: { name: "A. Nortje", overs: "3.2", runs: 28, wickets: 1 },
        crr: "9.55",
        rrr: "11.2",
        recentBalls: ["1", "4", "0", "1", "2", "6"],
      },
    },
  ],
  basketball: [
    {
      id: 1,
      teamA: "Lakers",
      teamB: "Warriors",
      scoreA: 108,
      scoreB: 112,
      currentQuarter: 4,
      gameClock: "02:34",
      quarterScoresA: [28, 24, 30, 26],
      quarterScoresB: [24, 30, 29, 29],
      shotClock: 24,
      status: "4th Quarter",
    },
    {
      id: 2,
      teamA: "Bulls",
      teamB: "Celtics",
      scoreA: 89,
      scoreB: 95,
      currentQuarter: 3,
      gameClock: "08:15",
      quarterScoresA: [22, 31, 36, 0],
      quarterScoresB: [27, 29, 39, 0],
      shotClock: 18,
      status: "3rd Quarter",
    },
  ],
  football: [
    {
      id: 1,
      teamA: "Manchester United",
      teamB: "Liverpool",
      scoreA: 2,
      scoreB: 1,
      matchTime: 78,
      half: 2,
      status: "Match in progress",
    },
    {
      id: 2,
      teamA: "Barcelona",
      teamB: "Real Madrid",
      scoreA: 1,
      scoreB: 3,
      matchTime: 90,
      half: 2,
      status: "Full Time",
    },
  ],
  tennis: [
    {
      id: 1,
      player1: "Novak Djokovic",
      player2: "Rafael Nadal",
      setsPlayer1: [6, 4, 6],
      setsPlayer2: [3, 6, 2],
      currentSet: 3,
      currentGameScorePlayer1: 30,
      currentGameScorePlayer2: 15,
      server: 1,
      status: "Set 3",
    },
    {
      id: 2,
      player1: "Roger Federer",
      player2: "Andy Murray",
      setsPlayer1: [7, 6],
      setsPlayer2: [5, 4],
      currentSet: 2,
      currentGameScorePlayer1: 40,
      currentGameScorePlayer2: 30,
      server: 1,
      status: "Set 2",
    },
  ],
  badminton: [
    {
      id: 1,
      player1: "Lin Dan",
      player2: "Lee Chong Wei",
      gamesPlayer1: [21, 18, 21],
      gamesPlayer2: [19, 21, 16],
      currentGame: 3,
      currentPointsPlayer1: 21,
      currentPointsPlayer2: 16,
      server: 1,
      bestOf: 3,
      status: "Lin Dan won",
    },
    {
      id: 2,
      player1: "P.V. Sindhu",
      player2: "Carolina Marin",
      gamesPlayer1: [21, 15],
      gamesPlayer2: [17, 21],
      currentGame: 3,
      currentPointsPlayer1: 11,
      currentPointsPlayer2: 9,
      server: 2,
      bestOf: 3,
      status: "Game 3 in progress",
    },
  ],
  volleyball: [
    {
      id: 1,
      teamA: "Brazil",
      teamB: "USA",
      setsTeamA: [25, 21, 24, 18],
      setsTeamB: [23, 25, 26, 25],
      currentSet: 4,
      currentPointsTeamA: 18,
      currentPointsTeamB: 25,
      setWinsA: 1,
      setWinsB: 3,
      bestOf: 5,
      status: "USA won",
    },
    {
      id: 2,
      teamA: "Italy",
      teamB: "Poland",
      setsTeamA: [25, 22, 25],
      setsTeamB: [20, 25, 19],
      currentSet: 3,
      currentPointsTeamA: 25,
      currentPointsTeamB: 19,
      setWinsA: 2,
      setWinsB: 1,
      bestOf: 5,
      status: "Set 4 pending",
    },
  ],
  kabaddi: [
    {
      id: 1,
      teamA: "Patna Pirates",
      teamB: "Bengal Warriors",
      scoreA: 32,
      scoreB: 28,
      playersOnMatA: 6,
      playersOnMatB: 5,
      raidTimer: 15,
      raidingTeam: "Patna Pirates",
      bonusActive: false,
      superRaidActive: false,
      half: 2,
      timeRemaining: "08:30",
      status: "2nd Half - 8:30 remaining",
    },
    {
      id: 2,
      teamA: "U Mumba",
      teamB: "Jaipur Pink Panthers",
      scoreA: 24,
      scoreB: 31,
      playersOnMatA: 7,
      playersOnMatB: 6,
      raidTimer: 8,
      raidingTeam: "Jaipur Pink Panthers",
      bonusActive: true,
      superRaidActive: false,
      half: 1,
      timeRemaining: "12:45",
      status: "1st Half - 12:45 remaining",
    },
  ],
  frisbee: [
    {
      id: 1,
      teamA: "Wind Chill",
      teamB: "Machine",
      scoreA: 12,
      scoreB: 9,
      timeRemaining: "15:30",
      pointCap: 15,
      possession: "Wind Chill",
      status: "2nd half",
    },
    {
      id: 2,
      teamA: "Revolution",
      teamB: "Empire",
      scoreA: 8,
      scoreB: 11,
      timeRemaining: "22:15",
      pointCap: 15,
      possession: "Empire",
      status: "2nd half",
    },
  ],
};

const deepClone = (value) => JSON.parse(JSON.stringify(value));

const getInitialMatches = (sport) => deepClone(initialMatchesBySport[sport] || []);

const getNextCounter = (matches) => {
  const maxId = matches.reduce((max, match) => {
    if (typeof match.id === "number" && match.id > max) {
      return match.id;
    }
    return max;
  }, 0);

  return maxId + 1;
};

module.exports = {
  getInitialMatches,
  getNextCounter,
};
